### ISSUE TITLE
message.id is not a function

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-Communication#69]
When running Tonomy Communication **inside a Docker** container the following error appears

See it in "stopped container" here https://github.com/Tonomy-Foundation/Tonomy-ID-SDK/actions/runs/6030618552/job/16362812711

To replicate
```bash
docker build . -t micro
docker run --name micro micro
```

Error

```bash
[Nest] 29  - 08/31/2023, 2:12:02 PM     LOG [NestFactory] Starting Nest application...
[Nest] 29  - 08/31/2023, 2:12:02 PM     LOG [InstanceLoader] AppModule dependencies initialized +14ms
[Nest] 29  - 08/31/2023, 2:12:02 PM     LOG [InstanceLoader] UsersModule dependencies initialized +0ms
TypeError: message.id is not a function
    at /app/node_modules/@asyncapi/react-component/src/containers/Sidebar/Sidebar.tsx:51:64
    at Array.map (<anonymous>)
    at Sidebar (/app/node_modules/@asyncapi/react-component/src/containers/Sidebar/Sidebar.tsx:44:35)
    at processChild (/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at Object.renderToString (/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at Context.renderSpec (/app/node_modules/@asyncapi/html-template/filters/all.js:165:25)
    at eval (eval at _compile (/app/node_modules/nunjucks/src/environment.js:527:18), <anonymous>:38:97)
```

**Comment by theblockstalk** [comment]
At this point the error is different
https://github.com/Tonomy-Foundation/Tonomy-Communication/pull/34

When `nestjs-asyncapi` is removed error is gone (tested on current `master` branch)
